### ISSUE TITLE
Container doesn't start - "exec: \"scripts/entrypoint.sh\": permission denied".

### ISSUE THREAD

**Issue by NiKrause** [Doichain/docker#1]
Steps to reproduce: 

1. ``git clone https://github.com/Doichain/docker.git``
2. Switch to branch 0.0.1 ``cd docker; git checkout 0.0.1``
3. Build docker image with: ``docker build .`` - wait 
4. Start container with: ``docker run -it doichain/dapp bash``

docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"scripts/entrypoint.sh\": permission denied".

**Comment by Ocean15** [comment]
Fixed [82de46e7348b8968d857da4e663e91fd08bdad0c](https://github.com/Doichain/docker/commit/82de46e7348b8968d857da4e663e91fd08bdad0c)

**Comment by NiKrause** [comment]
seems to be fixed in version 0.0.1 (see commit: https://github.com/Doichain/docker/commit/82de46e7348b8968d857da4e663e91fd08bdad0c )
