### ISSUE TITLE
RPC_PASSWORD shouldn't have a default

### ISSUE THREAD

**Issue by Ocean15** [Doichain/docker#5]
The docker env "RPC_PASSWORD" shouldn't have a default password set. It's a potential security lack

**Comment by NiKrause** [comment]
please also see: https://github.com/Doichain/dapp/issues/25
rpc-password should be generated during installation and then inserted into namecoin.conf and used in settings.json

default username and password in REST-interface (admin/password) must be also replaced and could be the same in my opinion.

other possibility, when starting a docker image the setup process (all parameters) are setup via the web interface. This way also the RPC username and authentication, as the default admin REST account  could be setup. https://github.com/Doichain/dapp/issues/25

**Comment by NiKrause** [comment]
echo -e "rpcuser=bitcoinrpc\nrpcpassword=$(xxd -l 16 -p /dev/urandom)" > "/Users/${USER}/Library/Application Support/Bitcoin/bitcoin.conf"

chmod 600 "/Users/${USER}/Library/Application Support/Bitcoin/bitcoin.conf"
