### ISSUE TITLE
Dapp isnt bundled

### ISSUE THREAD

**Issue by Ocean15** [Doichain/docker#9]
The meteor project should be bundled before it is used as a live dapp

**Comment by NiKrause** [comment]
in my opinion this is only important when the web app works as a standard web application. 
Since we don't use it as a mobile app yet and only for a couple of concurrent users as a decentralized system this seems lower priority.

**Comment by NiKrause** [comment]
Just in case its getting important: 

https://stackoverflow.com/questions/25677701/how-to-run-meteor-forever-and-is-it-good-using-3rd-party-database#25677859

**Comment by NiKrause** [comment]
Here is the example on how to bundle the meteor app and run it inside docker via npm https://projectricochet.com/blog/production-meteor-and-node-using-docker-part-i

**Comment by NiKrause** [comment]
We bundle Bob's dApp for the BasicDOITest in Jenkins now inside doichain/dapp-only image.
This should be integrated into 
- docker image doichain/dapp  and the
- manual installation procedure for non-docker installation
